# Generated by Django 5.1.5 on 2025-01-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('episode_number', models.IntegerField(unique=True)),
                ('duration', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_podcast_url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-episode_number'],
            },
        ),
    ]
