# Generated by Django 5.1.5 on 2025-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guest_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='guest_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
